name: build envps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: make
      - uses: actions/upload-artifact@v4
        with:
          name: envps-macos
          path: envps
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: make
      - uses: actions/upload-artifact@v4
        with:
          name: envps-linux
          path: envps
  build-freebsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        uses: cross-platform-actions/action@v0.32.0
        with:
          operating_system: freebsd
          version: '14.2'
          run: sudo pkg install -y gmake && gmake
      - uses: actions/upload-artifact@v4
        with:
          name: envps-freebsd
          path: envps
  build-netbsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        uses: cross-platform-actions/action@v0.32.0
        with:
          operating_system: netbsd
          version: '10.1'
          run: sudo pkgin -y install gmake && gmake
      - uses: actions/upload-artifact@v4
        with:
          name: envps-netbsd
          path: envps
